[profile.default]
src = "contracts"
out = "out"
test = "tests"
libs = ["lib", "node_modules"]
solc_version = "0.8.24"
evm_version = 'shanghai'
optimizer = true
optimizer_runs = 200
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

[profile.lint]
ignore = ["test/**/*"]
